### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by isaacmeira** [isaacmeira/personalwb#3]
- [x] Change the topography and the layout
 - [x] Add some text effects
 - [x] Add some layout effects.
 - [x] Edit the responsive.css
 - [x] Publish
